# No error
try:

    x = x + 2

except:

    print("Something went wrong")

else:

    print(f"Value of x is {x}")




# # With error

# try:

#     print(y)

# except:

#     print("Something went wrong")

# else:

#     print(f"Value of x is {y}")

# finally:

#     print("code block executed")